name: meme_editor_app
description: "Meme editor app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  http: ^1.4.0
  get_it: ^8.0.3
  go_router: ^14.1.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  saver_gallery: ^4.0.1
  permission_handler: ^11.3.1
  widgets_to_image: ^2.0.1
  google_fonts: ^6.2.1
  share_plus: ^11.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  riverpod_lint: ^2.6.5
  test: ^1.24.9
  mockito: ^5.4.6

flutter:
  uses-material-design: true